2 feat adicionar funções para o repositório usuário
ceos-jr/Atlas pull request #67
Opened 2023-08-09 21:15 UTC by juliatakimaki

# Description
Funções CreateUser, GetAllUsers e GetUserbyId

Closes # (linke sua issue aqui)

## Tipo de mudança

- [ ] Bug fix (mudança não críticaque conserta uma issue)
- [x] New feature (mudança não crítica que adiciona uma nova feature)
- [ ] Mudança crítica (Concerto ou uma feature que pode quebrar funcionalidades antigas)
- [ ] Apenas mudança de documentação

# Como ele tem sido testado?

- [ ] Teste A
- [ ] Teste B

**Configuração de testes**:

- Firmware version:
- Hardware:
- Toolchain:

# Checklist:

- [ ] Realizei uma revisão do meu código
- [x] Eu comentei meus códigos, particularmente nas aŕeas mais difíceis
- [ ] Eu fiz as mudanças correspondentes na documentação
- [ ] Minhas mudanças não geraram nenhum warning
- [ ] Adicionei testes que comprovam que minha correção é eficaz ou que minha feature funciona
- [ ] Testes unitários novos e já pre-existentes foram aprovados localmente
- [ ] Qualquer mudança pendente na main branch já foi implementada nessa branch

2023-08-09 22:55 UTC, Lu1z-Gust4v0 commented on backend/repositories/user.go
Feedback: 

- Melhore a posição dos comentários e deixa-los mais curtos
- Adicione um error handling explicito para as funções: 

```go
// Nós precisamos explicitamente retornar um `nil` na posição do parametros do usuário, 
// senão você vai retornar um endereço para uma struct vazia.
if error != nil {
   return nil, error
} 
```

2023-08-09 23:01 UTC, juliatakimaki commented on backend/repositories/user.go
Certo, eu posso tirar os comentários depois, fiz isso só pra não me perder. Vou ajustar o resto. 
👍

2023-08-10 13:32 UTC, Pedro6508 reviewed
Júlia acho que já está ok, eu vou fazer um PR tbm mostrando como eu implementei do meu jeito e acredito que o LG deve fazer do dele. Ai hoje e amanhã a gente vai juntar todos esses códigos e padroniza-los.

2023-08-10 22:19 UTC, Lu1z-Gust4v0 commented
## Atualizações

Renomei os commits para seguir o padrão

2023-08-14 00:28 UTC, Lu1z-Gust4v0 requested changes

2023-08-14 00:28 UTC, Lu1z-Gust4v0 commented on backend/repositories/user/implementation.go
## Considerações 

- Tome cuidado com os switch cases no seu código, identifiquei um switch case que vai retornar um erro 
se o tentarmos dar "update" sem atualizar o "status" 

- Não é necessário checar timestamps pois o gorm modifica isso automaticamente. Algo útil é colocar `time.Now()` quando realizmos um update bem sucedido. 

- Tente simplificar o código, acredito que essa não seja a versão final, porém está muito bagunçado. 

- Apague os comentários desnecessários. 

- Evite utilizar dois idiomas para o comentários, o padrão que estamos utilizando é comentar em ingles.

2023-08-14 00:28 UTC, Lu1z-Gust4v0 commented on backend/repositories/user/interface.go
## Considerações

- Excelente ideia de explicitamente definir um tamanho limite para os campos.
- Não faz sentido o tamanho minimo do email ser de `5`
- Não acho necessário passar o `timestamp` como parametro dessas funções

2023-08-14 18:09 UTC, Pedro6508 commented on backend/repositories/user/interface.go
# Tamanho mínimo email
Passarei o tamanho mínimo do email de 5 para 3. Diferente do anterior esse novo valor é embasado em [algo](https://stackoverflow.com/questions/1423195/what-is-the-actual-minimum-length-of-an-email-address-as-defined-by-the-ietf).

2023-08-14 21:28 UTC, Lu1z-Gust4v0 commented
## Feedback 

- Os pontos adereçados foram resolvidos
- Deixei de citar que teremos que fazer o hash das senhas, como o hash tem um tamanho especifico, definir um tamanho minimo para a senha não tem sentido nesse nivel. O check deve ser feito em outro lugar. Entretanto, não se preocupe com isso agora, quando o implementarmos, o hash será feito na função de create.
 
 ## Sugestão de mudanças
 
 - Simplificar os checks que você colocou nas funções
 - O  `limit` não está implementado de maneira correta, porém podemos deixar isso para uma nova issue.

2023-08-15 04:21 UTC, Pedro6508 approved these changes

2023-08-15 04:22 UTC, merged