Criar controller de usuario
ceos-jr/Atlas pull request #92
Opened 2023-09-15 00:40 UTC by Lu1z-Gust4v0

# Description

Criei uma estrutura para os controllers na nossa aplicação baseado no padrão dos repositories. Ele consiste em centralizar os controllers em uma struct principal que nos permite acessar todos os outros controllers, assim, facilitando o setup e melhorando a organização do código

Closes #87 

## Tipo de mudança

- [ ] Bug fix (mudança não críticaque conserta uma issue)
- [x] New feature (mudança não crítica que adiciona uma nova feature)
- [ ] Mudança crítica (Concerto ou uma feature que pode quebrar funcionalidades antigas)
- [ ] Apenas mudança de documentação

# Checklist:

- [x] Realizei uma revisão do meu código
- [ ] Eu comentei meus códigos, particularmente nas aŕeas mais difíceis
- [x] Eu fiz as mudanças correspondentes na documentação
- [x] Minhas mudanças não geraram nenhum warning
- [ ] Adicionei testes que comprovam que minha correção é eficaz ou que minha feature funciona
- [ ] Testes unitários novos e já pre-existentes foram aprovados localmente
- [x] Qualquer mudança pendente na main branch já foi implementada nessa branch

2023-09-15 05:59 UTC, Pedro6508 requested changes

2023-09-15 05:59 UTC, Pedro6508 commented on backend/tests/integration/service/userService/userService_test.go
# userService_test incompleto
Aparentemente múltiplas issues estão sendo resolvidas nessa branch, então para o PR ser aprovado todos os packages novos devem ao menos compilar e esse `userservicerepotest` em questão não compila.

2023-09-15 23:06 UTC, Lu1z-Gust4v0 commented on backend/tests/integration/service/userService/userService_test.go
O gabriel irá terminar esse, portanto aprove logo e ele manda as mudanças depois

2023-09-16 00:21 UTC, Pedro6508 approved these changes

2023-09-16 17:04 UTC, merged